### ISSUE TITLE
Refactor ISGCI

### ISSUE THREAD

**Issue by TAKeanice** [SPUNIKNSS15/SPUNIKNSS15_GraphInformation#31]
At least, CopyFromComplement shall be refactored to be a class method. Graphs should never exist without their complements.

**Comment by owdmn** [comment]
All subclasses of SmallGraph use buildComplement() from now on, which returns a new instance of the respective class, containing its complement. The complement links are still set correctly and the output didn't change at all. 

I also did some cleanup in the smallgraphs package and merged the commits into master.

Still todo: Refactor xml/SmallGraphReader, especially we need to transform for loops into for-each loops and type the vectors wherever possible so that unnecessary casts can be avoided.

**Comment by TAKeanice** [comment]
Take care on that conversion until you are very sure, that the upper bounds of the array don´t change during the loop. Also, is buildComplement() a static method? Can you reference a commit or branch here to be able to find the changes?

**Comment by TAKeanice** [comment]
@momits this is finished, right?
